### ISSUE TITLE
_TokenVariables.scss changes and removes variables from v2.7.3 to 2.8

### ISSUE THREAD

**Issue by geoffrey1218** [AlaskaAirlines/OrionDesignTokens#15]
# Issue report

Your issue may already be reported! Please search on the issue tracker before creating one.

## Expected Behavior

Upgrading to 2.8 does not remove or change the generated Sass variables in _TokenVariables.scss for backwards compatibility with existing projects.

## Current Behavior

Upgrading to 2.8 removes and changes several variables in _TokenVariables.scss.

$color-background-booking-bar, $color-background-footer, $color-background-account-drawer, $color-background-logo, $color-brand-blue-midnight-base, $color-type-theme-classic-primary, and $color-type-theme-classic-link-hover all change from #01426a to #156fad.

$color-classic-atlas, $color-classic-breeze, $color-classic-tropical, $color-classic-orca, $depth-hidden, $depth-dialog, $depth-overlay, $depth-modal, $depth-tooltip, and $shadow-box-shadow-classic have all been removed. 

## Possible Solution

For the changed tokens, set color.brand.blue.midnight.base to color.brand.midnight.400.value instead of color.brand.midnight.300.value.

Restore the removed tokens.

## Steps to Reproduce (for bugs)

Compare the generated _TokenVariables.scss file between 2.7.3 and 2.8.0. Note the changed/removed variables as listed above.

## Your Environment

* Version used: 2.8.0

**Comment by blackfalcon** [comment]
I think what you are reporting as a bug is a feature. 

By design, a legacy file like `_TokenVariables.scss` is only outputting the Orion design tokens. The new Auro tokens have vastly different names and uses, so many of the legacy tokens are deprecated. While many values are the same, many are new and many have been deprecated. 

Please see https://github.com/AlaskaAirlines/OrionDesignTokens#managing-deprecated-resources for more details on this matter. 

The 2.8 release was to allow for dev to migrate legacy code to the new token system. 3.0 will not be released until we have confidence that the Orion tokens have been fully deprecated.

**Comment by blackfalcon** [comment]
Sorry ... I read that wrong. I understand what you are saying and I will look into this ASAP.
